### ISSUE TITLE
[EPIC 1] Bundle proposal tx

### ISSUE THREAD

**Issue by wtfsayo** [SmartInvoiceXYZ/nouns-builder#1]
- [x] Find Bundling Approach
- [x] Write Bundler SC
- [x] Deploy to Sepolia & Holesky
- [x] Create first escrow from UI
- [x] Handle Native Token ~
- [ ] Deploy to Base, Zora, OP mainnet & testnets
- [ ] Deploy to ETH Mainnet

**Comment by b3nedictvs** [comment]
- bundler smart contract takes invoice address and uses it as receiver for the proposal
    - Is it possible to predict the deterministic address with the salt?
    - If we can predict the address and use it in a bundled transactions, then we would not need the bundler to create the invoice upfront.
- Alternate: take the transaction and create a deterministic address

**Comment by scottrepreneur** [comment]
Bundle these in the proposal txs instead

**Comment by b3nedictvs** [comment]
Found a small vulnerability

- one creates an invoice and the second sends funds to the invoice
- If the invoice cannot be created deterministically, a malicious actor may substitute the invoice address with their own invoice.
    - In this case, the proposal would fail.
    - Rough UX and small vulnerability.
- We want to bundle the smart contracts instead.

**Comment by b3nedictvs** [comment]
Are we able to access the execution transaction hash with the creation of the proposal? If so, we can find the address for funding and releasing funds.

**Comment by b3nedictvs** [comment]
Answer to this question is **NO**.



> Are we able to access the execution transaction hash with the creation of the proposal? If so, we can find the address for funding and releasing funds.

**Comment by b3nedictvs** [comment]
Metadata needs to be pinned before adding proposal description and title. As of right now only metadata for milestones can be added to metadata by @wtfsayo.

**Comment by b3nedictvs** [comment]
@wtfsayo will be testing the flow with bundle tx this week on sepolia. Once this everything is tested, we can deploy across networks Nouns Builder supports.

**Comment by wtfsayo** [comment]
Updated the tasks!!

**Comment by b3nedictvs** [comment]
@dan13ram will hold off from deployment until proposal passed and E2E flow could been tested
