### ISSUE TITLE
[EPIC 5] Organisational Integration and Funding

### ISSUE THREAD

**Issue by b3nedictvs** [SmartInvoiceXYZ/nouns-builder#5]
- [ ] creat PR on their repository with the updated code base
- [ ] work together with Nouns Builder to get it merged
- [ ] submit funding for work done to Nouns Builder
- [ ] take it to a community call and get a temperature check (midpoint target for the built)
