### ISSUE TITLE
[STORY 2-3] Update the ipfs metadata json schema and support milestone specific data (also applies to creation)

### ISSUE THREAD

**Issue by wtfsayo** [SmartInvoiceXYZ/nouns-builder#8]
- [ ] add image support for entire invoice
- [ ] Add metadata for each milestone
    - [ ] Title
    - [ ] estimated proposal
    - [ ] Add image

We will be relying on IPFS rather than updating the subgraph with this functionality as Nouns Builder is solely relying on IPFS metadata anyway.

**Comment by b3nedictvs** [comment]
- [ ] add image support for entire invoice
- [ ] Add metadata for each milestone
    - [ ] Title
    - [ ] estimated proposal
    - [ ] Add image

We will be relying on IPFS rather than updating the subgraph with this functionality as Nouns Builder is solely relying on IPFS metadata anyway.

**Comment by dan13ram** [comment]
Currently 
```
{
  projectName: "Project Name",
  projectDescription: "Description of the project",
  projectAgreement: [{
    type: "https", // or "ipfs"
    src: "https://urlToAgreement.com",
    createdAt: "seconds since epoch"
  }],
  startDate: UNIX_TIMESTAMP,
  endDate: UNIX_TIMESTAMP,
  klerosCourt: 1 (or 2 or 3)
}
```

Proposed 
```
{
  version: "v0.1.0",
  // @deprecated in favor of title
  projectName: "Project Name",
  title: "Project Name",
  // @deprecated in favor of description
  projectDescription: "Description of the project",
  description: "Description of the project",
  // @deprecated in favor of documents
  projectAgreement: [{
    id: 1,
    type: "https", // or "ipfs"
    src: "https://urlToAgreement.com",
    createdAt: "seconds since epoch"
  }],
  documents: [{
    id: 1,
    type: "https", // or "ipfs"
    src: "https://urlToAgreement.com",
    createdAt: "seconds since epoch"
  }],
  startDate: "seconds since epoch",
  endDate: "seconds since epoch",
  klerosCourt: 1, // (or 2 or 3),
  image: {
    id: 1,
    type: "https", // or "ipfs"
    src: "https://urlToImage",
    createdAt: "seconds since epoch"
  },
  milestones: [{
    id: 1,
    title: "Milestone 1",
    description: "Milestone description", 
    image: {
      id: 1,
      type: "https", // or "ipfs"
      src: "https://urlToImage",
      createdAt: "seconds since epoch"
    },
    documents: [{
      id: 1,
      type: "https", // or "ipfs"
      src: "https://urlToAgreement.com",
      createdAt: "seconds since epoch"
    }],
    endDate: "seconds since epoch",
  }]
}
```

**Comment by b3nedictvs** [comment]
- one image supported in the metadata, and only one image is supported in the UI
    - further images both for proposal and milestone are handled as documents
    - could handle the specification for the frontend through mime types (optional)
- parsing of metadata should be improved
